FROM MYSQL:latest

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=api_user
ENV MYSQL_PASSWORD=api_password
ENV MYSQL_DATABASE=db_project

# Copia script SQL a carpeta /docker-entrypoint-initdb.d/
COPY ./script.sql /docker-entrypoint-initdb.d/

EXPOSE 3306